### ISSUE TITLE
Problems making solution with CMake

### ISSUE THREAD

**Issue by Helioform** [arx/ArxWindows#4]
I get this error after I use CMake:

CMake Error at CMakeLists.txt:33 (add_subdirectory):
  The source directory

    C:/Git/ArxWindows/arx

  does not contain a CMakeLists.txt file.

I tried to fix the issue by removing the (add_subdirectory) instruction in the CMakeLists.txt file but I get an incomplete solution afterwards.

Thanks.

**Comment by dscharrer** [comment]
Please follow the [build instructions on the wiki](http://wiki.arx-libertatis.org/Downloading_and_Compiling_under_Windows), in particular the step about getting the Arx Libertatis source code:

    git submodule update --init --remote --recursive

I have also updated the README to include these instructions.
